export const {
  ADD_PRODUCT,
  DECREMENT_PRODUCT_AMOUNT,
  INCREMENT_PRODUCT_AMOUNT,
  REMOVE_PRODUCT,
} = {
  ADD_PRODUCT: 'ADD_PRODUCT',
  DECREMENT_PRODUCT_AMOUNT: 'DECREMENT_PRODUCT_AMOUNT',
  INCREMENT_PRODUCT_AMOUNT: 'INCREMENT_PRODUCT_AMOUNT',
  REMOVE_PRODUCT: 'REMOVE_PRODUCT',
};