export const {
  ADD_PRODUCT,
  CALC_PRODUCT_PRICE,
  CALC_TOTAL_PRICE,
  CLEAR_CART,
  DECREMENT_PRODUCT_AMOUNT,
  INCREMENT_PRODUCT_AMOUNT,
  REMOVE_PRODUCT,
} = {
  ADD_PRODUCT: 'ADD_PRODUCT',
  CALC_PRODUCT_PRICE: 'CALC_PRODUCT_PRICE',
  CALC_TOTAL_PRICE: 'CALC_TOTAL_PRICE',
  CLEAR_CART: 'CLEAR_CART',
  DECREMENT_PRODUCT_AMOUNT: 'DECREMENT_PRODUCT_AMOUNT',
  INCREMENT_PRODUCT_AMOUNT: 'INCREMENT_PRODUCT_AMOUNT',
  REMOVE_PRODUCT: 'REMOVE_PRODUCT',
};